# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  # - windows waiting for CMake fix on windows/juliia 1.3
julia:
  - 1.2
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/rafaqz/ArchGDAL.jl", rev="formattypes"))'
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

# jobs:
#   include:
#     - stage: "Documentation"
#       julia: 1.0
#       os: linux
#       script:
#         - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
#         - julia --project=docs/ --color=yes docs/make.jl
#       name: "HTML"
#       after_success: skip
#   services: docker
