name = "GeoData"
uuid = "9b6fcbb8-86d6-11e9-1ce7-23a6bb139a78"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.3.3"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
GeoFormatTypes = "68eda718-8dee-11e9-39e7-89f7f65f511f"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
Adapt = "2"
ArchGDAL = "0.5"
DimensionalData = "^0.15.2"
GeoFormatTypes = "^0.2.1, 0.3"
HDF5 = "0.14"
Missings = "0.4"
NCDatasets = "0.10"
ProgressMeter = "1"
RecipesBase = "0.7, 0.8, 1.0"
Reexport = "0.2"
Requires = "0.5, 1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
CFTime = "179af706-886a-5703-950a-314cd64e0468"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ArchGDAL", "CFTime", "HDF5", "NCDatasets", "Plots", "SafeTestsets", "Statistics", "Test"]
